// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using dotnet_store.Models;

#nullable disable

namespace dotnet_store.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20251009220654_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("dotnet_store.Models.Urun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Fiyat")
                        .HasColumnType("REAL");

                    b.Property<string>("UrunAd")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Urunler");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Active = false,
                            Fiyat = 30000.0,
                            UrunAd = "Apple Watch 7"
                        },
                        new
                        {
                            Id = 2,
                            Active = true,
                            Fiyat = 40000.0,
                            UrunAd = "Apple Watch 8"
                        },
                        new
                        {
                            Id = 3,
                            Active = true,
                            Fiyat = 50000.0,
                            UrunAd = "Apple Watch 9"
                        },
                        new
                        {
                            Id = 4,
                            Active = false,
                            Fiyat = 60000.0,
                            UrunAd = "Apple Watch 10"
                        },
                        new
                        {
                            Id = 5,
                            Active = true,
                            Fiyat = 70000.0,
                            UrunAd = "Apple Watch 11"
                        },
                        new
                        {
                            Id = 6,
                            Active = true,
                            Fiyat = 80000.0,
                            UrunAd = "Apple Watch 12"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
